In [49]:
profiles=['i love dogs','some cats, i like', 'i love nlp']

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

In [52]:
count_vectorizer=CountVectorizer()

In [53]:
vsm=count_vectorizer.fit_transform(profiles)

In [56]:
import pandas as pd

In [57]:
pd.DataFrame(vsm.todense(), columns=count_vectorizer.get_feature_names())

cats  dogs  like  love  nlp  some
0     0     1     0     1    0     0
1     1     0     1     0    0     1
2     0     0     0     1    1     0

In [58]:
query=['must love cats and dogs']

In [61]:
## Vectorize the query
query_vector=count_vectorizer.transform(query)

In [72]:
query_vector

<1x6 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [76]:
from sklearn.metrics.pairwise import cosine_similarity

In [79]:
similarity_vals=cosine_similarity(query_vector, vsm)[0]

In [80]:
similarity_vals

array([0.81649658, 0.33333333, 0.40824829])

In [81]:
import numpy as np

In [84]:
rankings=np.argsort(similarity_vals)[::-1]

In [85]:
rankings

array([0, 2, 1])

In [87]:
[profiles[i] for i in rankings]

['i love dogs', 'i love nlp', 'some cats, i like']

In [88]:
####

In [89]:
## cosine_sim(query , doc_i) =  dot(query_v, doc_i_vec)/ ||query_vec||||doc_i_vec||

In [102]:
np.dot(query_vector, vsm.T)/(np.linalg.norm(query_vector.todense(), axis=1)*np.linalg.norm(vsm.todense(), axis=1))

matrix([[0.81649658, 0.33333333, 0.40824829]])